-- Badge Migration: Extracted 309 badges from members.html
-- Generated on: 2026-02-07T16:06:56.192Z

-- First, remove the old seed badges to replace with comprehensive set
DELETE FROM public.badge_definitions WHERE id NOT IN (SELECT badge_id FROM public.user_badges);

-- Insert all badges (ON CONFLICT to handle existing ones)
INSERT INTO public.badge_definitions (id, name, description, icon, category, xp_reward, requirement_type, requirement_value, requirement_action, is_hidden, rarity) VALUES
  ('streak-streak-1', 'First Step', '1 week streak', '🌱', 'streak', 0, 'streak', 1, 'streak', false, 'common'),
  ('streak-streak-2', 'Growing Strong', '2 week streak', '🌿', 'streak', 0, 'streak', 2, 'streak', false, 'common'),
  ('streak-streak-3', 'Taking Root', '3 week streak', '🌳', 'streak', 0, 'streak', 3, 'streak', false, 'common'),
  ('streak-streak-4', 'On Fire', '4 week streak', '🔥', 'streak', 0, 'streak', 4, 'streak', false, 'common'),
  ('streak-streak-5', 'Flame Keeper', '5 week streak', '🔥', 'streak', 0, 'streak', 5, 'streak', false, 'common'),
  ('streak-streak-6', 'Lightning', '6 week streak', '⚡', 'streak', 0, 'streak', 6, 'streak', false, 'common'),
  ('streak-streak-7', 'Star Power', '7 week streak', '🌟', 'streak', 0, 'streak', 7, 'streak', false, 'common'),
  ('streak-streak-8', 'Diamond Streak', '8 week streak', '💎', 'streak', 0, 'streak', 8, 'streak', false, 'common'),
  ('streak-streak-10', 'Rocket', '10 week streak', '🚀', 'streak', 0, 'streak', 10, 'streak', false, 'common'),
  ('streak-streak-12', '3-Month Warrior', '12 week streak', '💪', 'streak', 0, 'streak', 12, 'streak', false, 'uncommon'),
  ('streak-streak-16', 'Lion Heart', '16 week streak', '🦁', 'streak', 0, 'streak', 16, 'streak', false, 'uncommon'),
  ('streak-streak-20', 'Dragon Mode', '20 week streak', '🐉', 'streak', 0, 'streak', 20, 'streak', false, 'uncommon'),
  ('streak-streak-26', 'Half-Year Hero', '26 week streak', '🏆', 'streak', 0, 'streak', 26, 'streak', false, 'rare'),
  ('streak-streak-30', 'Tidal Wave', '30 week streak', '🌊', 'streak', 0, 'streak', 30, 'streak', false, 'rare'),
  ('streak-streak-36', 'Mountain Peak', '36 week streak', '🏔️', 'streak', 0, 'streak', 36, 'streak', false, 'rare'),
  ('streak-streak-40', 'Soaring Eagle', '40 week streak', '🦅', 'streak', 0, 'streak', 40, 'streak', false, 'rare'),
  ('streak-streak-45', 'Volcanic', '45 week streak', '🌋', 'streak', 0, 'streak', 45, 'streak', false, 'rare'),
  ('streak-streak-50', 'Unstoppable', '50 week streak', '⚔️', 'streak', 0, 'streak', 50, 'streak', false, 'rare'),
  ('streak-streak-52', 'Year-Long Legend', '52 week streak', '👑', 'streak', 0, 'streak', 52, 'streak', false, 'epic'),
  ('streak-streak-75', 'Cosmic Dedication', '75 week streak', '🌠', 'streak', 0, 'streak', 75, 'streak', false, 'epic'),
  ('streak-streak-100', 'Century Club', '100 week streak', '🏛️', 'streak', 0, 'streak', 100, 'streak', false, 'legendary'),
  ('streak-streak-104', 'Two-Year Titan', '104 week streak', '👼', 'streak', 0, 'streak', 104, 'streak', false, 'legendary'),
  ('streak-streak-150', 'Mystical Master', '150 week streak', '🔮', 'streak', 0, 'streak', 150, 'streak', false, 'legendary'),
  ('streak-streak-156', 'Three-Year Legend', '156 week streak', '🎭', 'streak', 0, 'streak', 156, 'streak', false, 'legendary'),
  ('challenge-completed-1', 'First Challenge', 'Complete 1 challenge', '✅', 'challenge', 0, 'count', 1, 'completed', false, 'common'),
  ('challenge-completed-3', 'Getting Started', 'Complete 3 challenges', '📋', 'challenge', 0, 'count', 3, 'completed', false, 'common'),
  ('challenge-completed-5', 'High Five', 'Complete 5 challenges', '🎯', 'challenge', 0, 'count', 5, 'completed', false, 'common'),
  ('challenge-completed-10', 'Perfect Ten', 'Complete 10 challenges', '🔟', 'challenge', 0, 'count', 10, 'completed', false, 'common'),
  ('challenge-completed-15', 'Game On', 'Complete 15 challenges', '🎮', 'challenge', 0, 'count', 15, 'completed', false, 'common'),
  ('challenge-completed-20', 'Score Twenty', 'Complete 20 challenges', '🥳', 'challenge', 0, 'count', 20, 'completed', false, 'common'),
  ('challenge-completed-25', 'Quarter Century', 'Complete 25 challenges', '💫', 'challenge', 0, 'count', 25, 'completed', false, 'common'),
  ('challenge-completed-30', 'Thirty Strong', 'Complete 30 challenges', '🎲', 'challenge', 0, 'count', 30, 'completed', false, 'common'),
  ('challenge-completed-40', 'Forty Niner', 'Complete 40 challenges', '🎱', 'challenge', 0, 'count', 40, 'completed', false, 'common'),
  ('challenge-completed-50', 'Half Century', 'Complete 50 challenges', '🌟', 'challenge', 0, 'count', 50, 'completed', false, 'uncommon'),
  ('challenge-completed-60', 'Sixty Sensation', 'Complete 60 challenges', '🎪', 'challenge', 0, 'count', 60, 'completed', false, 'uncommon'),
  ('challenge-completed-75', 'Diamond Challenger', 'Complete 75 challenges', '💎', 'challenge', 0, 'count', 75, 'completed', false, 'uncommon'),
  ('challenge-completed-100', 'Century Slammer', 'Complete 100 challenges', '💯', 'challenge', 0, 'count', 100, 'completed', false, 'rare'),
  ('challenge-completed-125', 'Challenge Addict', 'Complete 125 challenges', '🎰', 'challenge', 0, 'count', 125, 'completed', false, 'rare'),
  ('challenge-completed-150', 'Rainbow Warrior', 'Complete 150 challenges', '🌈', 'challenge', 0, 'count', 150, 'completed', false, 'rare'),
  ('challenge-completed-175', 'Metamorphosis', 'Complete 175 challenges', '🦋', 'challenge', 0, 'count', 175, 'completed', false, 'rare'),
  ('challenge-completed-200', 'Double Century', 'Complete 200 challenges', '🏅', 'challenge', 0, 'count', 200, 'completed', false, 'rare'),
  ('challenge-completed-250', 'Quarter Millennium', 'Complete 250 challenges', '🎖️', 'challenge', 0, 'count', 250, 'completed', false, 'epic'),
  ('challenge-completed-300', 'Triple Century', 'Complete 300 challenges', '🏆', 'challenge', 0, 'count', 300, 'completed', false, 'epic'),
  ('challenge-completed-365', 'Daily Dedication', 'Complete 365 challenges', '📅', 'challenge', 0, 'count', 365, 'completed', false, 'epic'),
  ('challenge-completed-400', 'Quad Century', 'Complete 400 challenges', '🎯', 'challenge', 0, 'count', 400, 'completed', false, 'epic'),
  ('challenge-completed-500', 'Challenge King', 'Complete 500 challenges', '👑', 'challenge', 0, 'count', 500, 'completed', false, 'legendary'),
  ('challenge-completed-750', 'Hall of Fame', 'Complete 750 challenges', '🏛️', 'challenge', 0, 'count', 750, 'completed', false, 'legendary'),
  ('challenge-completed-1000', 'Grand Master', 'Complete 1000 challenges', '🌟', 'challenge', 0, 'count', 1000, 'completed', false, 'legendary'),
  ('contest-wins-1', 'First Win', 'Win 1 contest', '🥇', 'contest', 0, 'count', 1, 'wins', false, 'common'),
  ('contest-wins-2', 'Double Victory', 'Win 2 contests', '✌️', 'contest', 0, 'count', 2, 'wins', false, 'common'),
  ('contest-wins-3', 'Hat Trick', 'Win 3 contests', '🎯', 'contest', 0, 'count', 3, 'wins', false, 'common'),
  ('contest-wins-5', 'High Five Champion', 'Win 5 contests', '🖐️', 'contest', 0, 'count', 5, 'wins', false, 'common'),
  ('contest-wins-7', 'Lucky Seven', 'Win 7 contests', '🍀', 'contest', 0, 'count', 7, 'wins', false, 'common'),
  ('contest-wins-10', 'Perfect 10', 'Win 10 contests', '🔟', 'contest', 0, 'count', 10, 'wins', false, 'common'),
  ('contest-wins-15', 'Rising Star', 'Win 15 contests', '💫', 'contest', 0, 'count', 15, 'wins', false, 'uncommon'),
  ('contest-wins-20', 'Superstar', 'Win 20 contests', '🌟', 'contest', 0, 'count', 20, 'wins', false, 'uncommon'),
  ('contest-wins-25', 'Quarter Champion', 'Win 25 contests', '🏆', 'contest', 0, 'count', 25, 'wins', false, 'uncommon'),
  ('contest-wins-30', 'Thirty Crusher', 'Win 30 contests', '👊', 'contest', 0, 'count', 30, 'wins', false, 'uncommon'),
  ('contest-wins-40', 'Powerhouse', 'Win 40 contests', '💪', 'contest', 0, 'count', 40, 'wins', false, 'uncommon'),
  ('contest-wins-50', 'Fifty Fighter', 'Win 50 contests', '🥊', 'contest', 0, 'count', 50, 'wins', false, 'rare'),
  ('contest-wins-75', 'Contest Warrior', 'Win 75 contests', '⚔️', 'contest', 0, 'count', 75, 'wins', false, 'rare'),
  ('contest-wins-100', 'Century Champion', 'Win 100 contests', '👑', 'contest', 0, 'count', 100, 'wins', false, 'epic'),
  ('contest-wins-150', 'Dragon Slayer', 'Win 150 contests', '🐉', 'contest', 0, 'count', 150, 'wins', false, 'epic'),
  ('contest-wins-200', 'Contest Legend', 'Win 200 contests', '🏛️', 'contest', 0, 'count', 200, 'wins', false, 'legendary'),
  ('contest-submissions-1', 'First Submission', 'Submit 1 video', '📹', 'contest', 0, 'count', 1, 'submissions', false, 'common'),
  ('contest-submissions-5', 'Video Star', 'Submit 5 videos', '🎬', 'contest', 0, 'count', 5, 'submissions', false, 'common'),
  ('contest-submissions-10', 'Content Creator', 'Submit 10 videos', '🎥', 'contest', 0, 'count', 10, 'submissions', false, 'common'),
  ('contest-submissions-25', 'Film Director', 'Submit 25 videos', '📽️', 'contest', 0, 'count', 25, 'submissions', false, 'uncommon'),
  ('contest-submissions-50', 'Hollywood Star', 'Submit 50 videos', '🎞️', 'contest', 0, 'count', 50, 'submissions', false, 'rare'),
  ('contest-submissions-100', 'Video Legend', 'Submit 100 videos', '🎦', 'contest', 0, 'count', 100, 'submissions', false, 'epic'),
  ('points-points-50', 'First Coins', 'Earn 50 points', '🪙', 'points', 0, 'count', 50, 'points', false, 'common'),
  ('points-points-100', 'Century Points', 'Earn 100 points', '💰', 'points', 0, 'count', 100, 'points', false, 'common'),
  ('points-points-250', 'Point Collector', 'Earn 250 points', '💵', 'points', 0, 'count', 250, 'points', false, 'common'),
  ('points-points-500', 'Half Grand', 'Earn 500 points', '💎', 'points', 0, 'count', 500, 'points', false, 'common'),
  ('points-points-750', 'Rising Earner', 'Earn 750 points', '📈', 'points', 0, 'count', 750, 'points', false, 'common'),
  ('points-points-1000', '1K Club', 'Earn 1,000 points', '🏆', 'points', 0, 'count', 1000, 'points', false, 'common'),
  ('points-points-1500', 'Point Star', 'Earn 1,500 points', '💫', 'points', 0, 'count', 1500, 'points', false, 'common'),
  ('points-points-2000', '2K Achiever', 'Earn 2,000 points', '🌟', 'points', 0, 'count', 2000, 'points', false, 'uncommon'),
  ('points-points-2500', 'Quarter Master', 'Earn 2,500 points', '✨', 'points', 0, 'count', 2500, 'points', false, 'uncommon'),
  ('points-points-3000', '3K Blazer', 'Earn 3,000 points', '🔥', 'points', 0, 'count', 3000, 'points', false, 'uncommon'),
  ('points-points-4000', '4K Thunder', 'Earn 4,000 points', '⚡', 'points', 0, 'count', 4000, 'points', false, 'uncommon'),
  ('points-points-5000', '5K Royalty', 'Earn 5,000 points', '👑', 'points', 0, 'count', 5000, 'points', false, 'rare'),
  ('points-points-7500', 'Point Lion', 'Earn 7,500 points', '🦁', 'points', 0, 'count', 7500, 'points', false, 'rare'),
  ('points-points-10000', '10K Emperor', 'Earn 10,000 points', '🏛️', 'points', 0, 'count', 10000, 'points', false, 'epic'),
  ('points-points-15000', '15K Dragon', 'Earn 15,000 points', '🐉', 'points', 0, 'count', 15000, 'points', false, 'epic'),
  ('points-points-20000', '20K Volcanic', 'Earn 20,000 points', '🌋', 'points', 0, 'count', 20000, 'points', false, 'epic'),
  ('points-points-25000', '25K General', 'Earn 25,000 points', '🎖️', 'points', 0, 'count', 25000, 'points', false, 'epic'),
  ('points-points-50000', '50K Legend', 'Earn 50,000 points', '🏅', 'points', 0, 'count', 50000, 'points', false, 'legendary'),
  ('points-points-100000', '100K Immortal', 'Earn 100,000 points', '💎', 'points', 0, 'count', 100000, 'points', false, 'legendary'),
  ('points-spent-100', 'First Purchase', 'Spend 100 points', '🛒', 'points', 0, 'count', 100, 'spent', false, 'epic'),
  ('points-spent-500', 'Shopper', 'Spend 500 points', '🛍️', 'points', 0, 'count', 500, 'spent', false, 'legendary'),
  ('points-spent-1000', 'Big Spender', 'Spend 1,000 points', '🎁', 'points', 0, 'count', 1000, 'spent', false, 'legendary'),
  ('points-spent-5000', 'Point Mogul', 'Spend 5,000 points', '💸', 'points', 0, 'count', 5000, 'spent', false, 'legendary'),
  ('social-referrals-1', 'First Referral', 'Refer 1 friend', '🤝', 'social', 0, 'count', 1, 'referrals', false, 'common'),
  ('social-referrals-3', 'Friend Maker', 'Refer 3 friends', '👥', 'social', 0, 'count', 3, 'referrals', false, 'common'),
  ('social-referrals-5', 'Party Starter', 'Refer 5 friends', '🎉', 'social', 0, 'count', 5, 'referrals', false, 'common'),
  ('social-referrals-10', 'Network Builder', 'Refer 10 friends', '🌐', 'social', 0, 'count', 10, 'referrals', false, 'uncommon'),
  ('social-referrals-25', 'Community Builder', 'Refer 25 friends', '🏘️', 'social', 0, 'count', 25, 'referrals', false, 'rare'),
  ('social-referrals-50', 'Ambassador', 'Refer 50 friends', '🏛️', 'social', 0, 'count', 50, 'referrals', false, 'epic'),
  ('social-referrals-100', 'Referral King', 'Refer 100 friends', '👑', 'social', 0, 'count', 100, 'referrals', false, 'legendary'),
  ('social-votes-1', 'First Vote', 'Vote in 1 contest', '🗳️', 'social', 0, 'count', 1, 'votes', false, 'common'),
  ('social-votes-5', 'Active Voter', 'Vote in 5 contests', '✋', 'social', 0, 'count', 5, 'votes', false, 'common'),
  ('social-votes-10', 'Dedicated Voter', 'Vote in 10 contests', '🎯', 'social', 0, 'count', 10, 'votes', false, 'common'),
  ('social-votes-25', 'Poll Expert', 'Vote in 25 contests', '📊', 'social', 0, 'count', 25, 'votes', false, 'uncommon'),
  ('social-votes-50', 'Vote Champion', 'Vote in 50 contests', '🏆', 'social', 0, 'count', 50, 'votes', false, 'rare'),
  ('social-votes-100', 'Vote Legend', 'Vote in 100 contests', '👑', 'social', 0, 'count', 100, 'votes', false, 'epic'),
  ('social-reactions-1', 'First Reaction', 'Give 1 reaction', '🔥', 'social', 0, 'count', 1, 'reactions', false, 'common'),
  ('social-reactions-10', 'Reactor', 'Give 10 reactions', '😍', 'social', 0, 'count', 10, 'reactions', false, 'common'),
  ('social-reactions-50', 'Emoji Master', 'Give 50 reactions', '🎭', 'social', 0, 'count', 50, 'reactions', false, 'rare'),
  ('social-reactions-100', 'Reaction Pro', 'Give 100 reactions', '🌈', 'social', 0, 'count', 100, 'reactions', false, 'epic'),
  ('social-reactions-500', 'Reaction Storm', 'Give 500 reactions', '⚡', 'social', 0, 'count', 500, 'reactions', false, 'legendary'),
  ('social-reactionsReceived-10', 'Loved', 'Receive 10 reactions', '❤️', 'social', 0, 'count', 10, 'reactionsReceived', false, 'common'),
  ('social-reactionsReceived-50', 'Fan Favorite', 'Receive 50 reactions', '💕', 'social', 0, 'count', 50, 'reactionsReceived', false, 'rare'),
  ('social-reactionsReceived-100', 'Community Star', 'Receive 100 reactions', '🌟', 'social', 0, 'count', 100, 'reactionsReceived', false, 'epic'),
  ('social-reactionsReceived-500', 'Reaction Royalty', 'Receive 500 reactions', '👑', 'social', 0, 'count', 500, 'reactionsReceived', false, 'legendary'),
  ('social-polls-1', 'Poll Participant', 'Vote in 1 poll', '📋', 'social', 0, 'count', 1, 'polls', false, 'common'),
  ('social-polls-10', 'Poll Regular', 'Vote in 10 polls', '📊', 'social', 0, 'count', 10, 'polls', false, 'common'),
  ('social-polls-25', 'Poll Enthusiast', 'Vote in 25 polls', '🗳️', 'social', 0, 'count', 25, 'polls', false, 'uncommon'),
  ('social-polls-50', 'Poll Master', 'Vote in 50 polls', '🎯', 'social', 0, 'count', 50, 'polls', false, 'rare'),
  ('social-partners-1', 'First Partner', 'Connect with 1 partner', '🎾', 'social', 0, 'count', 1, 'partners', false, 'common'),
  ('social-partners-5', 'Social Player', 'Connect with 5 partners', '👫', 'social', 0, 'count', 5, 'partners', false, 'common'),
  ('social-partners-10', 'Network Pro', 'Connect with 10 partners', '🤝', 'social', 0, 'count', 10, 'partners', false, 'common'),
  ('social-partners-25', 'Connection Master', 'Connect with 25 partners', '🌐', 'social', 0, 'count', 25, 'partners', false, 'uncommon'),
  ('drills-drill-dinking-1', 'Dink Beginner', 'Complete 1 dink drill', '🎯', 'drills', 0, 'count', 1, 'drill-dinking', false, 'common'),
  ('drills-drill-dinking-5', 'Dink Apprentice', 'Complete 5 dink drills', '🎯', 'drills', 0, 'count', 5, 'drill-dinking', false, 'common'),
  ('drills-drill-dinking-10', 'Dink Specialist', 'Complete 10 dink drills', '🎯', 'drills', 0, 'count', 10, 'drill-dinking', false, 'common'),
  ('drills-drill-dinking-25', 'Dink Expert', 'Complete 25 dink drills', '🎯', 'drills', 0, 'count', 25, 'drill-dinking', false, 'uncommon'),
  ('drills-drill-dinking-50', 'Dink Master', 'Complete 50 dink drills', '🎯', 'drills', 0, 'count', 50, 'drill-dinking', false, 'rare'),
  ('drills-drill-dinking-100', 'Dink Legend', 'Complete 100 dink drills', '🎯', 'drills', 0, 'count', 100, 'drill-dinking', false, 'epic'),
  ('drills-drill-thirdshot-1', 'Drop Beginner', 'Complete 1 drop drill', '🪂', 'drills', 0, 'count', 1, 'drill-thirdshot', false, 'common'),
  ('drills-drill-thirdshot-5', 'Drop Apprentice', 'Complete 5 drop drills', '🪂', 'drills', 0, 'count', 5, 'drill-thirdshot', false, 'common'),
  ('drills-drill-thirdshot-10', 'Drop Specialist', 'Complete 10 drop drills', '🪂', 'drills', 0, 'count', 10, 'drill-thirdshot', false, 'common'),
  ('drills-drill-thirdshot-25', 'Drop Expert', 'Complete 25 drop drills', '🪂', 'drills', 0, 'count', 25, 'drill-thirdshot', false, 'uncommon'),
  ('drills-drill-thirdshot-50', 'Drop Master', 'Complete 50 drop drills', '🪂', 'drills', 0, 'count', 50, 'drill-thirdshot', false, 'rare'),
  ('drills-drill-thirdshot-100', 'Drop Legend', 'Complete 100 drop drills', '🪂', 'drills', 0, 'count', 100, 'drill-thirdshot', false, 'epic'),
  ('drills-drill-serve-1', 'Serve Beginner', 'Complete 1 serve drill', '🚀', 'drills', 0, 'count', 1, 'drill-serve', false, 'common'),
  ('drills-drill-serve-5', 'Serve Apprentice', 'Complete 5 serve drills', '🚀', 'drills', 0, 'count', 5, 'drill-serve', false, 'common'),
  ('drills-drill-serve-10', 'Serve Specialist', 'Complete 10 serve drills', '🚀', 'drills', 0, 'count', 10, 'drill-serve', false, 'common'),
  ('drills-drill-serve-25', 'Serve Expert', 'Complete 25 serve drills', '🚀', 'drills', 0, 'count', 25, 'drill-serve', false, 'uncommon'),
  ('drills-drill-serve-50', 'Serve Master', 'Complete 50 serve drills', '🚀', 'drills', 0, 'count', 50, 'drill-serve', false, 'rare'),
  ('drills-drill-serve-100', 'Serve Legend', 'Complete 100 serve drills', '🚀', 'drills', 0, 'count', 100, 'drill-serve', false, 'epic'),
  ('drills-drill-volley-1', 'Volley Beginner', 'Complete 1 volley drill', '⚡', 'drills', 0, 'count', 1, 'drill-volley', false, 'common'),
  ('drills-drill-volley-5', 'Volley Apprentice', 'Complete 5 volley drills', '⚡', 'drills', 0, 'count', 5, 'drill-volley', false, 'common'),
  ('drills-drill-volley-10', 'Volley Specialist', 'Complete 10 volley drills', '⚡', 'drills', 0, 'count', 10, 'drill-volley', false, 'common'),
  ('drills-drill-volley-25', 'Volley Expert', 'Complete 25 volley drills', '⚡', 'drills', 0, 'count', 25, 'drill-volley', false, 'uncommon'),
  ('drills-drill-volley-50', 'Volley Master', 'Complete 50 volley drills', '⚡', 'drills', 0, 'count', 50, 'drill-volley', false, 'rare'),
  ('drills-drill-volley-100', 'Volley Legend', 'Complete 100 volley drills', '⚡', 'drills', 0, 'count', 100, 'drill-volley', false, 'epic'),
  ('drills-drill-footwork-1', 'Footwork Beginner', 'Complete 1 footwork drill', '👟', 'drills', 0, 'count', 1, 'drill-footwork', false, 'common'),
  ('drills-drill-footwork-5', 'Footwork Apprentice', 'Complete 5 footwork drills', '👟', 'drills', 0, 'count', 5, 'drill-footwork', false, 'common'),
  ('drills-drill-footwork-10', 'Footwork Specialist', 'Complete 10 footwork drills', '👟', 'drills', 0, 'count', 10, 'drill-footwork', false, 'common'),
  ('drills-drill-footwork-25', 'Footwork Expert', 'Complete 25 footwork drills', '👟', 'drills', 0, 'count', 25, 'drill-footwork', false, 'uncommon'),
  ('drills-drill-footwork-50', 'Footwork Master', 'Complete 50 footwork drills', '👟', 'drills', 0, 'count', 50, 'drill-footwork', false, 'rare'),
  ('drills-drill-footwork-100', 'Footwork Legend', 'Complete 100 footwork drills', '👟', 'drills', 0, 'count', 100, 'drill-footwork', false, 'epic'),
  ('drills-drill-lob-1', 'Lob Beginner', 'Complete 1 lob drill', '🌙', 'drills', 0, 'count', 1, 'drill-lob', false, 'common'),
  ('drills-drill-lob-5', 'Lob Apprentice', 'Complete 5 lob drills', '🌙', 'drills', 0, 'count', 5, 'drill-lob', false, 'common'),
  ('drills-drill-lob-10', 'Lob Specialist', 'Complete 10 lob drills', '🌙', 'drills', 0, 'count', 10, 'drill-lob', false, 'common'),
  ('drills-drill-lob-25', 'Lob Expert', 'Complete 25 lob drills', '🌙', 'drills', 0, 'count', 25, 'drill-lob', false, 'uncommon'),
  ('drills-drill-lob-50', 'Lob Master', 'Complete 50 lob drills', '🌙', 'drills', 0, 'count', 50, 'drill-lob', false, 'rare'),
  ('drills-drill-lob-100', 'Lob Legend', 'Complete 100 lob drills', '🌙', 'drills', 0, 'count', 100, 'drill-lob', false, 'epic'),
  ('drills-drill-reset-1', 'Reset Beginner', 'Complete 1 reset drill', '🔄', 'drills', 0, 'count', 1, 'drill-reset', false, 'common'),
  ('drills-drill-reset-5', 'Reset Apprentice', 'Complete 5 reset drills', '🔄', 'drills', 0, 'count', 5, 'drill-reset', false, 'common'),
  ('drills-drill-reset-10', 'Reset Specialist', 'Complete 10 reset drills', '🔄', 'drills', 0, 'count', 10, 'drill-reset', false, 'common'),
  ('drills-drill-reset-25', 'Reset Expert', 'Complete 25 reset drills', '🔄', 'drills', 0, 'count', 25, 'drill-reset', false, 'uncommon'),
  ('drills-drill-reset-50', 'Reset Master', 'Complete 50 reset drills', '🔄', 'drills', 0, 'count', 50, 'drill-reset', false, 'rare'),
  ('drills-drill-reset-100', 'Reset Legend', 'Complete 100 reset drills', '🔄', 'drills', 0, 'count', 100, 'drill-reset', false, 'epic'),
  ('drills-drill-atp-1', 'ATP Beginner', 'Complete 1 ATP drill', '🌀', 'drills', 0, 'count', 1, 'drill-atp', false, 'common'),
  ('drills-drill-atp-5', 'ATP Apprentice', 'Complete 5 ATP drills', '🌀', 'drills', 0, 'count', 5, 'drill-atp', false, 'common'),
  ('drills-drill-atp-10', 'ATP Specialist', 'Complete 10 ATP drills', '🌀', 'drills', 0, 'count', 10, 'drill-atp', false, 'common'),
  ('drills-drill-atp-25', 'ATP Expert', 'Complete 25 ATP drills', '🌀', 'drills', 0, 'count', 25, 'drill-atp', false, 'uncommon'),
  ('drills-drill-atp-50', 'ATP Master', 'Complete 50 ATP drills', '🌀', 'drills', 0, 'count', 50, 'drill-atp', false, 'rare'),
  ('drills-drill-erne-1', 'Erne Beginner', 'Complete 1 Erne drill', '🦅', 'drills', 0, 'count', 1, 'drill-erne', false, 'common'),
  ('drills-drill-erne-5', 'Erne Apprentice', 'Complete 5 Erne drills', '🦅', 'drills', 0, 'count', 5, 'drill-erne', false, 'common'),
  ('drills-drill-erne-10', 'Erne Specialist', 'Complete 10 Erne drills', '🦅', 'drills', 0, 'count', 10, 'drill-erne', false, 'common'),
  ('drills-drill-erne-25', 'Erne Expert', 'Complete 25 Erne drills', '🦅', 'drills', 0, 'count', 25, 'drill-erne', false, 'uncommon'),
  ('drills-drill-erne-50', 'Erne Master', 'Complete 50 Erne drills', '🦅', 'drills', 0, 'count', 50, 'drill-erne', false, 'rare'),
  ('drills-drill-speedup-1', 'Firefight Beginner', 'Complete 1 speedup drill', '🔥', 'drills', 0, 'count', 1, 'drill-speedup', false, 'common'),
  ('drills-drill-speedup-5', 'Firefight Apprentice', 'Complete 5 speedup drills', '🔥', 'drills', 0, 'count', 5, 'drill-speedup', false, 'common'),
  ('drills-drill-speedup-10', 'Firefight Specialist', 'Complete 10 speedup drills', '🔥', 'drills', 0, 'count', 10, 'drill-speedup', false, 'common'),
  ('drills-drill-speedup-25', 'Firefight Expert', 'Complete 25 speedup drills', '🔥', 'drills', 0, 'count', 25, 'drill-speedup', false, 'uncommon'),
  ('drills-drill-speedup-50', 'Firefight Master', 'Complete 50 speedup drills', '🔥', 'drills', 0, 'count', 50, 'drill-speedup', false, 'rare'),
  ('time-membership-7', 'One Week In', 'Member for 1 week', '📅', 'time', 0, 'count', 7, 'membership', false, 'common'),
  ('time-membership-14', 'Two Weeks Strong', 'Member for 2 weeks', '🗓️', 'time', 0, 'count', 14, 'membership', false, 'common'),
  ('time-membership-30', 'One Month Member', 'Member for 1 month', '🌙', 'time', 0, 'count', 30, 'membership', false, 'common'),
  ('time-membership-60', 'Two Month Member', 'Member for 2 months', '🌓', 'time', 0, 'count', 60, 'membership', false, 'common'),
  ('time-membership-90', 'Quarter Year', 'Member for 3 months', '🌗', 'time', 0, 'count', 90, 'membership', false, 'uncommon'),
  ('time-membership-180', 'Half Year Hero', 'Member for 6 months', '🌕', 'time', 0, 'count', 180, 'membership', false, 'uncommon'),
  ('time-membership-270', 'Nine Month Veteran', 'Member for 9 months', '🌟', 'time', 0, 'count', 270, 'membership', false, 'uncommon'),
  ('time-membership-365', 'One Year Anniversary', 'Member for 1 year', '🎂', 'time', 0, 'count', 365, 'membership', false, 'rare'),
  ('time-membership-547', '18 Month Star', 'Member for 18 months', '⭐', 'time', 0, 'count', 547, 'membership', false, 'rare'),
  ('time-membership-730', 'Two Year Anniversary', 'Member for 2 years', '🎊', 'time', 0, 'count', 730, 'membership', false, 'epic'),
  ('time-membership-1095', 'Three Year Legend', 'Member for 3 years', '👑', 'time', 0, 'count', 1095, 'membership', false, 'legendary'),
  ('time-membership-1825', 'Five Year Immortal', 'Member for 5 years', '🏛️', 'time', 0, 'count', 1825, 'membership', false, 'legendary'),
  ('time-logins-3', '3-Day Login', 'Login 3 days in a row', '🌅', 'time', 0, 'streak', 3, 'logins', false, 'common'),
  ('time-logins-7', 'Week Warrior', 'Login 7 days in a row', '🌄', 'time', 0, 'streak', 7, 'logins', false, 'common'),
  ('time-logins-14', '2-Week Runner', 'Login 14 days in a row', '🏃', 'time', 0, 'streak', 14, 'logins', false, 'common'),
  ('time-logins-30', 'Monthly Master', 'Login 30 days in a row', '📆', 'time', 0, 'streak', 30, 'logins', false, 'rare'),
  ('time-logins-60', '60-Day Dedication', 'Login 60 days in a row', '💫', 'time', 0, 'streak', 60, 'logins', false, 'rare'),
  ('time-logins-90', '90-Day Blaze', 'Login 90 days in a row', '🔥', 'time', 0, 'streak', 90, 'logins', false, 'epic'),
  ('time-logins-180', '180-Day Lightning', 'Login 180 days in a row', '⚡', 'time', 0, 'streak', 180, 'logins', false, 'legendary'),
  ('time-logins-365', '365-Day King', 'Login every day for a year', '👑', 'time', 0, 'streak', 365, 'logins', false, 'legendary'),
  ('special-profile-1', 'Profile Started', 'Add basic info', '📝', 'special', 0, 'special', 1, 'profile', false, 'common'),
  ('special-profile-2', 'Picture Perfect', 'Add profile photo', '📷', 'special', 0, 'special', 2, 'profile', false, 'common'),
  ('special-profile-3', 'Profile Complete', 'Fill out entire profile', '✨', 'special', 0, 'special', 3, 'profile', false, 'common'),
  ('special-profile-4', 'DUPR Verified', 'Add your DUPR rating', '🎯', 'special', 0, 'special', 4, 'profile', false, 'common'),
  ('special-founder-1', 'Beta Tester', 'Joined during beta', '🚀', 'special', 0, 'special', 1, 'founder', false, 'common'),
  ('special-founder-2', 'Founding Member', 'First 100 members', '🌟', 'special', 0, 'special', 2, 'founder', false, 'common'),
  ('special-founder-3', 'Diamond Founder', 'First 50 members', '💎', 'special', 0, 'special', 3, 'founder', false, 'common'),
  ('special-founder-4', 'OG Member', 'First 10 members', '👑', 'special', 0, 'special', 4, 'founder', false, 'common'),
  ('special-perfectWeek-1', 'Perfect Week', 'Challenge + Contest + Vote', '🎯', 'special', 0, 'special', 1, 'perfectWeek', false, 'common'),
  ('special-perfectWeek-4', 'Perfect Month', '4 perfect weeks', '🌟', 'special', 0, 'special', 4, 'perfectWeek', false, 'common'),
  ('special-perfectWeek-12', 'Perfect Quarter', '12 perfect weeks', '💫', 'special', 0, 'special', 12, 'perfectWeek', false, 'common'),
  ('special-perfectWeek-52', 'Perfect Year', '52 perfect weeks', '👑', 'special', 0, 'special', 52, 'perfectWeek', false, 'rare'),
  ('special-comeback-1', 'Welcome Back', 'Return after 2 weeks', '🔙', 'special', 0, 'special', 1, 'comeback', false, 'common'),
  ('special-comeback-2', 'Phoenix Rising', 'Return after 1 month', '🦅', 'special', 0, 'special', 2, 'comeback', false, 'common'),
  ('special-comeback-3', 'The Return', 'Return after 3 months', '🌅', 'special', 0, 'special', 3, 'comeback', false, 'common'),
  ('special-winStreak-2', 'Double Win', 'Win 2 contests in a row', '🔥', 'special', 0, 'special', 2, 'winStreak', false, 'common'),
  ('special-winStreak-3', 'Triple Threat', 'Win 3 contests in a row', '⚡', 'special', 0, 'special', 3, 'winStreak', false, 'common'),
  ('special-winStreak-4', 'Quad Dominator', 'Win 4 contests in a row', '💫', 'special', 0, 'special', 4, 'winStreak', false, 'common'),
  ('special-winStreak-5', 'Unstoppable', 'Win 5 contests in a row', '👑', 'special', 0, 'special', 5, 'winStreak', false, 'common'),
  ('special-winStreak-10', 'Dynasty', 'Win 10 contests in a row', '🏛️', 'special', 0, 'special', 10, 'winStreak', false, 'common'),
  ('special-seasonal-1', 'Halloween Hustler', 'Active on Halloween', '🎃', 'special', 0, 'special', 1, 'seasonal', false, 'common'),
  ('special-seasonal-2', 'Thankful Player', 'Active on Thanksgiving', '🦃', 'special', 0, 'special', 2, 'seasonal', false, 'common'),
  ('special-seasonal-3', 'Holiday Hero', 'Active during holidays', '🎄', 'special', 0, 'special', 3, 'seasonal', false, 'common'),
  ('special-seasonal-4', 'New Year Champion', 'Active New Year''s Day', '🎆', 'special', 0, 'special', 4, 'seasonal', false, 'common'),
  ('special-seasonal-5', 'Valentine Victor', 'Active Valentine''s Day', '💝', 'special', 0, 'special', 5, 'seasonal', false, 'common'),
  ('special-seasonal-6', 'Lucky Charm', 'Active St. Patrick''s Day', '☘️', 'special', 0, 'special', 6, 'seasonal', false, 'common'),
  ('special-seasonal-7', 'Easter Ace', 'Active on Easter', '🐰', 'special', 0, 'special', 7, 'seasonal', false, 'common'),
  ('special-seasonal-8', 'Independence Star', 'Active July 4th', '🇺🇸', 'special', 0, 'special', 8, 'seasonal', false, 'common'),
  ('special-seasonal-9', 'Summer Slammer', 'Active summer season', '☀️', 'special', 0, 'special', 9, 'seasonal', false, 'common'),
  ('special-seasonal-10', 'Fall Fighter', 'Active fall season', '🍂', 'special', 0, 'special', 10, 'seasonal', false, 'common'),
  ('special-seasonal-11', 'Winter Warrior', 'Active winter season', '❄️', 'special', 0, 'special', 11, 'seasonal', false, 'common'),
  ('special-seasonal-12', 'Spring Sensation', 'Active spring season', '🌸', 'special', 0, 'special', 12, 'seasonal', false, 'common'),
  ('special-timeOfDay-1', 'Early Bird', 'Active before 6 AM', '🌅', 'special', 0, 'special', 1, 'timeOfDay', false, 'common'),
  ('special-timeOfDay-2', 'Night Owl', 'Active after midnight', '🦉', 'special', 0, 'special', 2, 'timeOfDay', false, 'common'),
  ('special-timeOfDay-3', 'Midnight Grinder', 'Active 10 nights', '🌙', 'special', 0, 'special', 3, 'timeOfDay', false, 'common'),
  ('special-timeOfDay-4', 'Morning Champion', 'Active 10 early mornings', '☀️', 'special', 0, 'special', 4, 'timeOfDay', false, 'common'),
  ('special-improvement-1', 'Rising Star', 'DUPR increased 0.1', '📈', 'special', 0, 'milestone', 1, 'improvement', false, 'common'),
  ('special-improvement-2', 'Level Up', 'DUPR increased 0.25', '🚀', 'special', 0, 'milestone', 2, 'improvement', false, 'common'),
  ('special-improvement-3', 'Major Breakthrough', 'DUPR increased 0.5', '⭐', 'special', 0, 'milestone', 3, 'improvement', false, 'common'),
  ('special-improvement-4', 'Transformation', 'DUPR increased 1.0', '🏆', 'special', 0, 'milestone', 4, 'improvement', false, 'common'),
  ('special-secret-1', '???', 'Hidden achievement', '🔮', 'special', 0, 'special', 1, 'secret', true, 'common'),
  ('special-secret-2', '???', 'Hidden achievement', '🎭', 'special', 0, 'special', 2, 'secret', true, 'common'),
  ('special-secret-3', '???', 'Hidden achievement', '🗝️', 'special', 0, 'special', 3, 'secret', true, 'common'),
  ('special-secret-4', '???', 'Hidden achievement', '🌈', 'special', 0, 'special', 4, 'secret', true, 'common'),
  ('special-secret-5', '???', 'Hidden achievement', '💫', 'special', 0, 'special', 5, 'secret', true, 'common'),
  ('leaderboard-leaderboard-50', 'Top 50', 'Reached Top 50', '📊', 'leaderboard', 0, 'milestone', 50, 'leaderboard', false, 'rare'),
  ('leaderboard-leaderboard-25', 'Top 25', 'Reached Top 25', '📈', 'leaderboard', 0, 'milestone', 25, 'leaderboard', false, 'uncommon'),
  ('leaderboard-leaderboard-10', 'Top 10', 'Reached Top 10', '🔟', 'leaderboard', 0, 'milestone', 10, 'leaderboard', false, 'common'),
  ('leaderboard-leaderboard-5', 'Top 5', 'Reached Top 5', '🖐️', 'leaderboard', 0, 'milestone', 5, 'leaderboard', false, 'common'),
  ('leaderboard-leaderboard-3', 'Top 3', 'Reached Top 3', '🥉', 'leaderboard', 0, 'milestone', 3, 'leaderboard', false, 'common'),
  ('leaderboard-leaderboard-2', 'Runner Up', 'Reached #2', '🥈', 'leaderboard', 0, 'milestone', 2, 'leaderboard', false, 'common'),
  ('leaderboard-leaderboard-1', '#1 Champion', 'Reached #1 spot', '🥇', 'leaderboard', 0, 'milestone', 1, 'leaderboard', false, 'common'),
  ('leaderboard-leaderboardStreak-2', 'Back-to-Back #1', '#1 twice in a row', '👑', 'leaderboard', 0, 'milestone', 2, 'leaderboardStreak', false, 'common'),
  ('featured-featured-1', 'Featured Video', 'Video was featured', '⭐', 'featured', 0, 'special', 1, 'featured', false, 'common'),
  ('featured-coachPick-1', 'Coach''s Pick', 'Selected by Coach Ray', '🎓', 'featured', 0, 'special', 1, 'coachPick', false, 'common'),
  ('featured-videoOfWeek-1', 'Video of the Week', 'Weekly top video', '📹', 'featured', 0, 'special', 1, 'videoOfWeek', false, 'common'),
  ('featured-videoOfMonth-1', 'Video of the Month', 'Monthly top video', '🎬', 'featured', 0, 'special', 1, 'videoOfMonth', false, 'common'),
  ('featured-viralVideo-1', 'Viral Video', '50+ votes on video', '🔥', 'featured', 0, 'special', 1, 'viralVideo', false, 'common'),
  ('featured-cinematic-1', 'Cinematic', 'Outstanding video quality', '🎥', 'featured', 0, 'special', 1, 'cinematic', false, 'common'),
  ('featured-trending-1', 'Trending', 'Video went trending', '📈', 'featured', 0, 'special', 1, 'trending', false, 'common'),
  ('featured-videoHallOfFame-1', 'Video Hall of Fame', 'All-time great video', '🏛️', 'featured', 0, 'special', 1, 'videoHallOfFame', false, 'common'),
  ('helper-helper-1', 'Welcome Wagon', 'Helped 1 new member', '👋', 'helper', 0, 'count', 1, 'helper', false, 'common'),
  ('helper-helper-5', 'Helpful Member', 'Helped 5 members', '🤗', 'helper', 0, 'count', 5, 'helper', false, 'common'),
  ('helper-helper-10', 'Mentor', 'Helped 10 members', '🧑‍🏫', 'helper', 0, 'count', 10, 'helper', false, 'common'),
  ('helper-helper-25', 'Community Guide', 'Helped 25 members', '🗺️', 'helper', 0, 'count', 25, 'helper', false, 'uncommon'),
  ('helper-helper-50', 'Community Leader', 'Helped 50 members', '🦸', 'helper', 0, 'count', 50, 'helper', false, 'rare'),
  ('helper-helper-100', 'Elder', 'Helped 100 members', '🧙', 'helper', 0, 'count', 100, 'helper', false, 'epic'),
  ('helper-helper-200', 'Pillar of Community', 'Helped 200 members', '🏛️', 'helper', 0, 'count', 200, 'helper', false, 'legendary'),
  ('helper-helper-500', 'Ambassador Elite', 'Helped 500 members', '👑', 'helper', 0, 'count', 500, 'helper', false, 'legendary'),
  ('skill-dupr-3', '3.0 Club', 'DUPR 3.0+', '🎾', 'skill', 0, 'milestone', 3, 'dupr', false, 'common'),
  ('skill-dupr-3.25', '3.25 Rising', 'DUPR 3.25+', '📈', 'skill', 0, 'milestone', 3.25, 'dupr', false, 'common'),
  ('skill-dupr-3.5', '3.5 Achiever', 'DUPR 3.5+', '⭐', 'skill', 0, 'milestone', 3.5, 'dupr', false, 'common'),
  ('skill-dupr-3.75', '3.75 Competitor', 'DUPR 3.75+', '🏅', 'skill', 0, 'milestone', 3.75, 'dupr', false, 'common'),
  ('skill-dupr-4', '4.0 Elite', 'DUPR 4.0+', '🔥', 'skill', 0, 'milestone', 4, 'dupr', false, 'common'),
  ('skill-dupr-4.25', '4.25 Advanced', 'DUPR 4.25+', '💪', 'skill', 0, 'milestone', 4.25, 'dupr', false, 'common'),
  ('skill-dupr-4.5', '4.5 Expert', 'DUPR 4.5+', '🌟', 'skill', 0, 'milestone', 4.5, 'dupr', false, 'common'),
  ('skill-dupr-4.75', '4.75 Pro', 'DUPR 4.75+', '⚡', 'skill', 0, 'milestone', 4.75, 'dupr', false, 'common'),
  ('skill-dupr-5', '5.0 Master', 'DUPR 5.0+', '🏆', 'skill', 0, 'milestone', 5, 'dupr', false, 'common'),
  ('skill-dupr-5.5', '5.5+ Legend', 'DUPR 5.5+', '👑', 'skill', 0, 'milestone', 5.5, 'dupr', false, 'common'),
  ('combo-combo-1', 'Daily Double', 'Challenge + Contest same day', '✌️', 'combo', 0, 'count', 1, 'combo', false, 'common'),
  ('combo-combo-2', 'Triple Threat', 'Challenge + Contest + Vote', '🎯', 'combo', 0, 'count', 2, 'combo', false, 'common'),
  ('combo-combo-3', 'Quad Force', 'All 4 activities in one week', '💥', 'combo', 0, 'count', 3, 'combo', false, 'common'),
  ('combo-combo-4', 'Social Butterfly', '5 reactions + vote + poll', '🦋', 'combo', 0, 'count', 4, 'combo', false, 'common'),
  ('combo-combo-5', 'Grinder', '3 challenges in one week', '⚙️', 'combo', 0, 'count', 5, 'combo', false, 'common'),
  ('combo-combo-6', 'Streak + Win', 'Win while on streak', '🔥', 'combo', 0, 'count', 6, 'combo', false, 'common'),
  ('combo-combo-7', 'Referral + Win', 'Refer friend & win same week', '🤝', 'combo', 0, 'count', 7, 'combo', false, 'common'),
  ('combo-combo-8', 'All-Rounder', '1 of everything in a month', '🌍', 'combo', 0, 'count', 8, 'combo', false, 'common'),
  ('combo-combo-9', 'Perfectionist', 'Perfect participation monthly', '💎', 'combo', 0, 'count', 9, 'combo', false, 'common'),
  ('combo-combo-10', 'Ultimate Achiever', 'All combos unlocked', '🏛️', 'combo', 0, 'count', 10, 'combo', false, 'common'),
  ('member-memberNumber-10', 'The Originals', 'Member #1-10', '🌟', 'member', 0, 'milestone', 10, 'memberNumber', false, 'common'),
  ('member-memberNumber-50', 'Early Adopter', 'Member #11-50', '🚀', 'member', 0, 'milestone', 50, 'memberNumber', false, 'rare'),
  ('member-memberNumber-100', 'Century Club', 'Member #51-100', '💯', 'member', 0, 'milestone', 100, 'memberNumber', false, 'epic'),
  ('member-memberNumber-250', 'Quarter Thousand', 'Member #101-250', '🎯', 'member', 0, 'milestone', 250, 'memberNumber', false, 'legendary'),
  ('member-memberNumber-500', 'Half Thousand', 'Member #251-500', '🏅', 'member', 0, 'milestone', 500, 'memberNumber', false, 'legendary'),
  ('member-memberNumber-1000', 'Millennium Member', 'Member #501-1000', '🎆', 'member', 0, 'milestone', 1000, 'memberNumber', false, 'legendary'),
  ('member-memberNumber-5000', '5K Era', 'Member #1001-5000', '🌍', 'member', 0, 'milestone', 5000, 'memberNumber', false, 'legendary'),
  ('member-memberNumber-10000', 'Growth Era', 'Member #5001+', '🌐', 'member', 0, 'milestone', 10000, 'memberNumber', false, 'legendary'),
  ('special-tips-1', 'Tip Submitter', 'Submitted 1 tip', '💡', 'special', 0, 'count', 1, 'tips', false, 'common'),
  ('special-tips-5', 'Tip Regular', 'Submitted 5 tips', '📝', 'special', 0, 'count', 5, 'tips', false, 'common'),
  ('special-featuredTip-1', 'Featured Tip', 'Tip was featured', '⭐', 'special', 0, 'count', 1, 'featuredTip', false, 'common'),
  ('special-featuredTip-10', 'Tip Master', '10 featured tips', '🎯', 'special', 0, 'count', 10, 'featuredTip', false, 'common'),
  ('special-featuredTip-25', 'Tip Legend', '25 featured tips', '🏆', 'special', 0, 'count', 25, 'featuredTip', false, 'uncommon'),
  ('special-tipHallOfFame-1', 'Tip Hall of Fame', 'All-time great tips', '🏛️', 'special', 0, 'special', 1, 'tipHallOfFame', false, 'common'),
  ('special-shoutouts-1', 'First Shoutout', 'Received 1 shoutout', '📢', 'special', 0, 'count', 1, 'shoutouts', false, 'common'),
  ('special-shoutouts-5', 'Shoutout Regular', 'Received 5 shoutouts', '🎤', 'special', 0, 'count', 5, 'shoutouts', false, 'common'),
  ('special-shoutouts-10', 'Shoutout Star', 'Received 10 shoutouts', '🌟', 'special', 0, 'count', 10, 'shoutouts', false, 'common'),
  ('special-wallOfFame-1', 'Wall of Fame', 'Inducted to Wall of Fame', '🖼️', 'special', 0, 'special', 1, 'wallOfFame', false, 'common'),
  ('special-shoutouts-25', 'Community Celebrity', 'Received 25 shoutouts', '🎭', 'special', 0, 'count', 25, 'shoutouts', false, 'uncommon'),
  ('special-shoutouts-50', 'Living Legend', 'Received 50 shoutouts', '👑', 'special', 0, 'count', 50, 'shoutouts', false, 'rare')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  icon = EXCLUDED.icon,
  category = EXCLUDED.category,
  requirement_type = EXCLUDED.requirement_type,
  requirement_value = EXCLUDED.requirement_value,
  requirement_action = EXCLUDED.requirement_action,
  is_hidden = EXCLUDED.is_hidden,
  rarity = EXCLUDED.rarity;

-- Summary:
-- Total badges: 309
-- By category:
--   drills: 57
--   special: 57
--   social: 30
--   streak: 24
--   challenge: 24
--   points: 23
--   contest: 22
--   time: 20
--   skill: 10
--   combo: 10
--   leaderboard: 8
--   featured: 8
--   helper: 8
--   member: 8
-- By rarity:
--   common: 176
--   rare: 40
--   uncommon: 37
--   epic: 29
--   legendary: 27
